### ISSUE TITLE
"Error: you must be logged in to the server" in tab completion

### ISSUE THREAD

**Issue by phmarek** [rottencandy/vimkubectl#7]
If you open `vim` and do `:Kedit <tab>` without being logged in, this text comes up as completion.

**Comment by phmarek** [comment]
`NVIM v0.9.4`; `strace` confirms that an error code is returned.

`:set verbose=255 verbosefile=/tmp/....` doesn't work for `Kedit <tab>` completion, though.

```
:echo system("oc project")
:echo v:shell_error
```
correctly gives 1.


8caac6c6332d0164fdca0c82e6532e2cfd9e66bb seems to help, though that's a bit brute-force and might cause other bugs.

**Comment by rottencandy** [comment]
Thx for the pointers, I think this wasn't reproducible for me was because of my kubectl version. It seems to silently fail without any message in case of invalid kubeconfig

**Comment by rottencandy** [comment]
I used your fix and let the caller handle the shell_error checks, 85a7e04 should fix this

I want to stop using `system()` and switch to async api soon.

**Comment by rottencandy** [comment]
Marking this as fixed, but feel free to reopen if issue persists
